backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Erstellungsdatum", name: "date", widget: "datetime"}
      - {label: "Oben anpinnen", name: "sticky", widget: "boolean", default: false }
      - {label: "In Seitenleiste anzeigen", name: "featured", widget: "boolean", default: false }
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Inhalt", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Statische Seiten"
    folder: "src/pages"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "static-page"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Überschrift anzeigen", name: "showTitle", widget: "boolean"}
      - label: "Home Section"
        name: "sections"
        widget: "list"
        types:
          - label: "Gallerie"
            name: "carousel"
            widget: object
            fields:
              - label: Bilder
                name: images
                widget: list
                fields: 
                  - {label: Bild, name: image, widget: image}
          - label: "Bild"
            name: "image"
            widget: object
            fields:
              - {label: Bild, name: image, widget: image}
          - label: "Inhalt"
            name: "body"
            widget: object
            fields:
              - {label: "Inhalt", name: "body", widget: "markdown"}
          - label: "Banner"
            name: "banner"
            widget: object
            fields:
              - {label: Offset, name: offset, widget: number, default: 0}
          - label: "Blogliste"
            name: "teaser_list"
            widget: object
            fields:
              - {label: Offset, name: offset, widget: number, default: 0}
              - {label: Count, name: count, widget: number, default: 3}
          - label: "iFrame"
            name: "iframe"
            widget: object
            fields:
              - {label: HTML, name: html, widget: text}
          - label: "Info"
            name: "info"
            widget: object
            fields:
              - {label: "Titel", name: "title", widget: "string"}

  - name: settings
    label: Einstellungen
    editor:
      preview: false
    delete: false
    files:
      - file: src/data/events.yml
        label: Veranstaltungen
        name: events
        fields:
          - label: Veranstaltung
            name: event_items
            widget: list
            fields:
              - {label: Veranstaltung, name: label, widget: string}
              - {label: Datum, name: date, widget: datetime}
              - {label: Beschreibung, name: description, widget: string}
      - file: src/data/menu.yml
        label: Navigation
        name: menu
        fields:
          - label: Eintrag
            name: menu_entry
            widget: list
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: Seite
                name: page
                widget: string
              - label: Eintrag
                name: menu_entry
                widget: list
                fields:
                  - label: "Titel"
                    name: "title"
                    widget: "string"
                  - label: "Seite"
                    name: "page"
                    widget: "relation"
                    collection: "pages"
                    displayFields: ["title"]
                    searchFields: ["title", "slug"]
                    valueField: "slug"
